config/routes.rb
Rails.application.routes.draw do
  get 'docs/index'
  devise_for :users, path: 'auth', :controllers => {:registrations => "registrations",  confirmations: 'confirmations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  
  resources :bsp_trainings
  resources :llc_services
  resources :medications
  resources :medication_counts
  resources :mars
  resources :behaviors
  resources :docs

  resources :users do
    get :reset_password, on: :member
    get 'settings', on: :collection
    get 'edit_password', on: :collection
    put 'update_password', on: :collection
  end
end

app/models/medication_count.rb
class MedicationCount < ApplicationRecord
  belongs_to :company
  belongs_to :user
  has_many :medication_count_items, dependent: :destroy
  accepts_nested_attributes_for :medication_count_items, allow_destroy: true, reject_if: :all_blank

  has_many :signature_lists, as: :signatureable, dependent: :destroy
  accepts_nested_attributes_for :signature_lists, allow_destroy: true, reject_if: :all_blank
end

app/controllers/medication_counts_controller.rb
class MedicationCountsController < ApplicationController

  before_action :authenticate_user!

  def index
    if current_user.admin?
      @medication_counts = current_company.medication_counts
    else
      @medication_counts = current_user.medication_counts
    end
  end

  def new
    @medication_count = current_company.medication_counts.new
    @medication_count.medication_count_items.build
    @medication_count.signature_lists.build
  end

  def create
    @medication_count =  current_company.medication_counts.new(medication_count_params)
    @medication_count.created_by = current_user.id
    @medication_count.edited_by = current_user.id
    if @medication_count.save
      flash[:notice] = "Medication Count is successfully created"
      redirect_to medication_counts_path
    else
      flash[:alert] = "Something worng please try again"
      render action: :new
    end
  end


  def show
    @medication_count = current_company.medication_counts.find_by_id(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render template: 'medication_counts/show', pdf: 'Medication Count Report-' + Time.now.strftime('%v %H:%M:%S').to_s,
               layout: 'pdf.html.erb', disposition: 'attachment'
      end
    end
  end

  def edit
    @medication_count = current_company.medication_counts.find_by_id(params[:id])
  end

  def update
    @medication_count = current_company.medication_counts.find_by_id(params[:id])
    @medication_count.edited_by = current_user.id
    if @medication_count.update_attributes(medication_count_params)
      flash[:notice] = "Medication Counts is successfully Saved"
      redirect_to medication_counts_path
    else
      flash[:alert] = "Something worng please try again"
      render action: :edit
    end
  end

  def destroy
    @medication_count = current_company.medication_counts.find_by_id(params[:id])
    if @medication_count.destroy
      flash[:notice] = "Medication Counts successfully deleted!"
    else
      flash[:alert] = "Something went wrong, please try again!"
    end
    redirect_to action: :index
  end


  private

  def medication_count_params
    params.require(:medication_count).permit!
  end
end

app/helpers/medication_counts_helper.rb
module MedicationCountsHelper
end

app/views/medication_counts/_form.html.erb
<%= form_for(@medication_count,html: {class: 'fromlist'}) do |f| %>
    <div class="col-sm-12" style="padding: 0px">
      <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
        <div class="form-group" >
          <%= f.label :user_id, "Individual", style: 'opacity: .5;' %><br />
          <%= f.select(:user_id, current_company.individuals.collect { |ind| [ind.full_name, ind.id] }, {}, { :class => 'form-control chosen-select', required: true}) %>
        </div>
      </div>

      <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
        <div class="form-group">
          <%= f.text_field :medication_order,class: 'form-control', required: true %>
          <%= f.label :medication_order, class: 'form-control-placeholder' %>
        </div>
      </div>
    </div>

    <div class="medication_count_-wrapper">
      <%= f.fields_for :medication_count_items do |ls| %>
          <%= render 'medication_counts/medication_counts_section', mdc: ls %>
      <% end %>
    </div>

    <div class="col-md-12 col-sm-12 col-lg-12 addfilds clearfix" id="">
      <a id="medication_count_add" class="addmore-btn" href="javascript:void(0);">
        <%= image_tag 'plus_icon.png' %>Add
        Medication Counts Field ( 2 )
      </a>
    </div>

    <div class="col-md-12 col-sm-12 col-lg-12 medicaldicsnew">Medical Discontinued</div>

    <div class="col-md-6 col-sm-12 savebut">
      <div class="form-group">
        <%= f.text_field :discontinued_date,class: 'form-control datepicker', required: true %>
        <%= f.label :discontinued_date, class: 'form-control-placeholder' %>
      </div>
    </div>

    <div class="col-md-6 col-sm-12 savebut">
      <div class="form-group">
        <%= f.text_field :medication_disposal_location,class: 'form-control', required: true %>
        <%= f.label :medication_disposal_location, class: 'form-control-placeholder' %>
      </div>
    </div>


    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="col-md-12 col-sm-12 col-lg-12 medicaldics">Signature Fields</div>
      <div class="signature-list-wrapper">
        <%= f.fields_for :signature_lists do |sl| %>
            <%= render 'shared/signature_lists', sl: sl %>
        <% end %>
      </div>
      <div class="col-md-4 col-sm-12 col-lg-4 addfilds">
        <a id="signature_add" class="addmore-btn" href="javascript:void(0);">
          <%= image_tag 'plus_icon.png' %>Add
          Signature Fields ( 2 )
        </a>
      </div>
    </div>


    <div class="col-md-12 col-sm-12 savebut">
      <button type="submit" class="btn btn-default">Save</button>
    </div>
<% end %>
<%= render 'shared/signature_modal' %>
<script type="text/javascript">
  $(document).ready(function(){

    $(function () {

      $('.datepicker').datepicker({

        format: 'yyyy/mm/dd',
        icons: {
          time: 'fa fa-clock',
          date: 'fa fa-calendar',
          up: 'fa fa-arrow-up',
          down: 'fa fa-arrow-down',
          previous: 'fa fa-chevron-left',
          next: 'fa fa-chevron-right',
          today: 'fa fa-calendar-check-o',
          clear: 'fa fa-trash',
          close: 'fa fa-times'

        },

      });

      $('.timepicker').datetimepicker({

        icons: {
          time: 'fa fa-clock',
          date: 'fa fa-calendar',
          up: 'fa fa-arrow-up',
          down: 'fa fa-arrow-down',
          previous: 'fa fa-chevron-left',
          next: 'fa fa-chevron-right',
          today: 'fa fa-calendar-check-o',
          clear: 'fa fa-trash',
          close: 'fa fa-times'

        },

        format: 'LT'
      });

    });

    $("#medication_count_add").on("click", function () {
      var serialNumber = new Date().getTime();
      var regexp = new RegExp('serial_number', 'g');
      $('.medication_count_-wrapper').append("<%= escape_javascript(render 'medication_counts/medication_count_item').html_safe %>".replace(regexp, serialNumber));
    });

    $("#signature_add").on("click", function () {
      var serialNumber = new Date().getTime();
      var regexp = new RegExp('serial_number', 'g');
      $('.signature-list-wrapper').append("<%= escape_javascript(render 'signature_list').html_safe %>".replace(regexp, serialNumber));
    });

  });

  $(function () {
    $(document).off('click', '.signature').on('click', '.signature', function () {
      var selector = this.id
      $("#exampleModal").modal().on('shown.bs.modal', function () {
        $(this).off('shown.bs.modal');
        drawSignature('#' + selector);
      });
    });
  });
</script>

app/views/medication_counts/_medication_count_item.html.erb
<div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
  <div class="form-group">
    <input class="form-control datepicker" name="medication_count[medication_count_items_attributes][serial_number][date]" id="medication_count_medication_count_items_attributes_serial_number_date" type="text">
    <label class="form-control-placeholder" for="medication_count_medication_count_items_attributes_serial_number_date">Date</label>
  </div>

  <div class="form-group">
    <input class="form-control" name="medication_count[medication_count_items_attributes][serial_number][amount_used]" id="medication_count_medication_count_items_attributes_serial_number_amount_used" type="text">
    <label class="form-control-placeholder" for="medication_count_medication_count_items_attributes_serial_number_amount_used">Amount used</label>
  </div>

  <div class="form-group">
    <input class="form-control" name="medication_count[medication_count_items_attributes][serial_number][amount_left]" id="medication_count_medication_count_items_attributes_serial_number_amount_left" type="text">
    <label class="form-control-placeholder" for="medication_count_medication_count_items_attributes_serial_number_amount_left">Amount left</label>
  </div>
</div>

<div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
  <div class="form-group">
    <input class="form-control timepicker" name="medication_count[medication_count_items_attributes][serial_number][time]" id="medication_count_medication_count_items_attributes_serial_number_time" type="text">
    <label class="form-control-placeholder" for="medication_count_medication_count_items_attributes_serial_number_time">Time</label>
  </div>

  <div class="form-group">
    <input class="form-control" name="medication_count[medication_count_items_attributes][serial_number][amount_on_hand]" id="medication_count_medication_count_items_attributes_serial_number_amount_on_hand" type="text">
    <label class="form-control-placeholder" for="medication_count_medication_count_items_attributes_serial_number_amount_on_hand">Amount on hand</label>
  </div>

  <div class="form-group">
    <input class="form-control" name="medication_count[medication_count_items_attributes][serial_number][staff_initials]" id="medication_count_medication_count_items_attributes_serial_number_staff_initials" type="text">
    <label class="form-control-placeholder" for="medication_count_medication_count_items_attributes_serial_number_staff_initials">Staff initials</label>
  </div>
</div>

<div class="col-md-12 col-sm-12 col-lg-12 col-xs-12">
  <div class="form-group">
    <input class="form-control datepicker" name="medication_count[medication_count_items_attributes][serial_number][date_of_update]" id="medication_count_medication_count_items_attributes_serial_number_date_of_update" type="text">
    <label class="form-control-placeholder" for="medication_count_medication_count_items_attributes_serial_number_date_of_update">Date of Update/Changes</label>
  </div>
</div>


<script type="text/javascript">
  $(document).ready(function(){

    $(function () {

      $('.datepicker').datepicker({

        format: 'yyyy/mm/dd',
        icons: {
          time: 'fa fa-clock',
          date: 'fa fa-calendar',
          up: 'fa fa-arrow-up',
          down: 'fa fa-arrow-down',
          previous: 'fa fa-chevron-left',
          next: 'fa fa-chevron-right',
          today: 'fa fa-calendar-check-o',
          clear: 'fa fa-trash',
          close: 'fa fa-times'

        },

      });

      $('.timepicker').datetimepicker({

        icons: {
          time: 'fa fa-clock',
          date: 'fa fa-calendar',
          up: 'fa fa-arrow-up',
          down: 'fa fa-arrow-down',
          previous: 'fa fa-chevron-left',
          next: 'fa fa-chevron-right',
          today: 'fa fa-calendar-check-o',
          clear: 'fa fa-trash',
          close: 'fa fa-times'

        },

        format: 'LT'
      });

    });

  });
</script>
    

app/views/medication_counts/_medication_counts_section.html.erb
<div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
  <div class="form-group">
    <%= mdc.text_field :date,class: 'form-control datepicker'%>
    <%= mdc.label :date, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= mdc.text_field :amount_used,class: 'form-control'%>
    <%= mdc.label :amount_used, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= mdc.text_field :amount_left,class: 'form-control'%>
    <%= mdc.label :amount_left, class: 'form-control-placeholder' %>
  </div>
</div>

<div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
  <div class="form-group">
    <%= mdc.text_field :time,class: 'form-control timepicker'%>
    <%= mdc.label :time, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= mdc.text_field :amount_on_hand,class: 'form-control'%>
    <%= mdc.label :amount_on_hand, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= mdc.text_field :staff_initials,class: 'form-control'%>
    <%= mdc.label :staff_initials, class: 'form-control-placeholder' %>
  </div>
</div>

<div class="col-md-12 col-sm-12 col-lg-12 col-xs-12">
  <div class="form-group">
    <%= mdc.text_field :date_of_update,class: 'form-control datepicker'%>
    <%= mdc.label :date_of_update, 'Date of Update/Changes', class: 'form-control-placeholder' %>
  </div>
</div>

app/views/medication_counts/_signature_list.html.erb
<div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
  <div class="form-group">
    <input class="form-control signature" readonly="readonly" name="medication_count[signature_lists_attributes][serial_number][signature]" id="medication_count_signature_lists_attributes_serial_number_signature" type="text">
    <label class="form-control-placeholder" for="medication_count_signature_lists_attributes_serial_number_signature">Signature</label>
  </div>
</div>

<div class="col-md-4 col-sm-4 col-lg-4 col-xs-4">
  <div class="form-group">
    <input class="form-control" name="medication_count[signature_lists_attributes][serial_number][initials]" id="medication_count_signature_lists_attributes_serial_number_initials" type="text">
    <label class="form-control-placeholder" for="medication_count_signature_lists_attributes_serial_number_initials">Initials</label>
  </div>
</div>
      

app/views/medication_counts/edit.html.erb
<div id="page-wrapper">
  <div class="row">
    <p>&nbsp;</p>
    <p><h1>Medication Count Edit</h1></p>
    <%= render 'form' %>
  </div>
</div>

app/views/medication_counts/index.html.erb
<div id="page-wrapper">
  <div class="row">
    <p>&nbsp;</p>
    <div class="panel panel-default">
      <div class="panel-heading indiviuals_list">
        Medications List

      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
              <th>S. No.</th>
              <th>Individual Name</th>
              <th>Date of Training</th>
              <th>Last Edited</th>
              <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
            <% @medication_counts.each_with_index do |medication_count, i| %>
                <tr>
                  <td><%= i + 1 %></td>
                  <td><%= medication_count.user.full_name if medication_count.user.present? %></td>
                  <td><%= medication_count.date %></td>
                  <td><%= medication_count.updated_at %></td>
                  <td><%= link_to edit_medication_count_path(medication_count) do %>
                        <%= image_tag 'setting.png' %> Edit
                    <% end %>
                  </td>
                  <td><%= link_to medication_count_path(medication_count) do %>
                        <i class="fa fa-eye"></i> View
                    <% end %>
                  </td>
                  <td><%= link_to  medication_count_path(medication_count,authenticity_token: form_authenticity_token), method: :delete, data: { confirm: 'Are you sure?' } do %>
                        <%= image_tag 'delete.png' %> Delete
                    <% end %>
                  </td>
                </tr>
                <tr>
            <% end %>
            </tbody>
          </table>
        </div>
        <!-- /.table-responsive -->
      </div>


      <!-- /.panel-body -->
    </div>
    <%= link_to 'Add New Entry', new_medication_count_path, class: 'btn add_entry' %>
  </div>
  <!-- /.row -->
</div>

app/views/medication_counts/new.html.erb
<div id="page-wrapper">
  <div class="row">
    <p>&nbsp;</p>
    <p><h1>Medication Count Create</h1> </p>
    <%= render 'form' %>
  </div>
</div>

app/views/medication_counts/show.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading indiviuals_list">
        Medication Count
      </div>
      </div>

    <table class="table medication-count-table ">

      <thead>
      <tr>
        <th class="text-center" colspan="6">Medication Count Sheet for Controlled Medications</th>
      </tr>
      <tr>
        <th colspan="4">Name: <%= @medication_count.user.full_name  if @medication_count.user.present? %></th>
      </tr>
      <tr class="table-area-field100">
        <th colspan="4">Medication Order:  <%= @medication_count.medication_order %></th>
      </tr>
      <!--<tr>-->
      <!--<th rowspan="2">Grade.</th>-->
      <!--<th rowspan="2">Yield Point.</th>-->
      <!--<th colspan="2">Ultimate tensile strength</th>-->
      <!--<th rowspan="2">Per cent elong. 50.8&nbsp;mm or&nbsp;2&nbsp;in.</th>-->
      <!--<th rowspan="2">Per cent reduct. area.</th>-->
      <!--</tr>-->
      <tr class="title-list">
        <th>Date</th>
        <th>Time</th>
        <th>Amount On Hand</th>
        <th>Amount Used</th>
        <th>Amount Left</th>
        <th class="min-width-250">Staff Initials</th>
      </tr>
      </thead>
      <tbody>
      <% @medication_count.medication_count_items.each do |mdc| %>
          <tr>
            <td><%= mdc.date %></td>
            <td><%= mdc.time %></td>
            <td><%= mdc.amount_on_hand %></td>
            <td><%= mdc.amount_used %></td>
            <td><%= mdc.amount_left %></td>
            <td><%= mdc.staff_initials %></td>
          </tr>
      <% end %>
      <tr>
        <td colspan="4"><strong>Medication Discontinued</strong></td>
        <td rowspan="2"><strong>Pharmacy Instructions:</strong></td>
        <td rowspan="">
          <strong>Medication Disposal:</strong>
          <%= @medication_count.medication_disposal_location %>
        </td>
      </tr>
      <tr>
        <td colspan="4">Discontinued Date:  <%= @medication_count.discontinued_date %></td>
      </tr>
      <tr>
        <td colspan="6" class="text-center"><strong>Certified Staff Signature & Initial:</strong></td>
      </tr>
      <% @medication_count.signature_lists.each do |sl| %>
          <tr>
            <td colspan="4"><%= image_tag sl.signature , style: "width:125px" %></td>
            <td colspan="4"><%= sl.initials %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
</div>
 </div>

<script type="text/javascript">
  $(".save-as-pdf" ).click(function() {
    window.location.replace("<%= medication_count_path(@medication_count, format: :pdf) %>")
  });
</script>

app/views/medication_counts/show.pdf.erb
<table class="table medication-count-table ">

  <thead>
  <tr>
    <th class="text-center" colspan="6">Medication Count Sheet for Controlled Medications</th>
  </tr>
  <tr>
    <th colspan="4">Name: <%= @medication_count.user.full_name  if @medication_count.user.present? %></th>
    <th colspan="4"  style="border-top: none"></th>
  </tr>
  <tr class="table-area-field100">
    <th colspan="4">Medication Order:  <%= @medication_count.medication_order %></th>
    <th colspan="4"  style="border-top: none"></th>
  </tr>
  <!--<tr>-->
  <!--<th rowspan="2">Grade.</th>-->
  <!--<th rowspan="2">Yield Point.</th>-->
  <!--<th colspan="2">Ultimate tensile strength</th>-->
  <!--<th rowspan="2">Per cent elong. 50.8&nbsp;mm or&nbsp;2&nbsp;in.</th>-->
  <!--<th rowspan="2">Per cent reduct. area.</th>-->
  <!--</tr>-->
  <tr class="title-list">
    <th>Date</th>
    <th>Time</th>
    <th>Amount On Hand</th>
    <th>Amount Used</th>
    <th>Amount Left</th>
    <th class="min-width-250">Staff Initials</th>
  </tr>
  </thead>
  <tbody>
  <% @medication_count.medication_count_items.each do |mdc| %>
      <tr>
        <td style="width: 120px"><%= mdc.date %></td>
        <td style="width: 100px"><%= mdc.time %></td>
        <td><%= mdc.amount_on_hand %></td>
        <td><%= mdc.amount_used %></td>
        <td><%= mdc.amount_left %></td>
        <td><%= mdc.staff_initials %></td>
      </tr>
  <% end %>
  <tr>
    <td colspan="4"><strong>Medication Discontinued</strong></td>
    <td rowspan="2"><strong>Pharmacy Instructions:</strong></td>
    <td rowspan="">
      <strong>Medication Disposal:</strong>
      <%= @medication_count.medication_disposal_location %>
    </td>
  </tr>
  <tr>
    <td colspan="4">Discontinued Date:  <%= @medication_count.discontinued_date %></td>
    <td colspan="4" style="border-top: none"></td>
  </tr>
  <tr>
    <td colspan="6" class="text-center"><strong>Certified Staff Signature & Initial:</strong></td>
  </tr>
  <% @medication_count.signature_lists.each do |sl| %>
      <tr>
        <td colspan="4"><%= image_tag sl.signature , style: "width:125px" %></td>
        <td colspan="4"><%= sl.initials %></td>
      </tr>
  <% end %>

  </tbody>
</table>