config/routes.rb
Rails.application.routes.draw do
  get 'docs/index'
  devise_for :users, path: 'auth', :controllers => {:registrations => "registrations",  confirmations: 'confirmations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  
  resources :bsp_trainings
  resources :llc_services
  resources :medications
  resources :medication_counts
  resources :mars
  resources :behaviors
  resources :docs

  resources :users do
    get :reset_password, on: :member
    get 'settings', on: :collection
    get 'edit_password', on: :collection
    put 'update_password', on: :collection
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  belongs_to :company, optional: true
  has_many :bsp_trainings
  has_many :llc_services
  has_many :medications
  has_many :medication_counts
  has_many :mars
  has_many :behaviors

  has_and_belongs_to_many :service_types

  after_create :send_welcome_email
  
  ROLES = {
    super_admin: 'super_admin',
    admin: 'admin',
    staff: 'staff',
    individual: 'individual'
  }

  ROLES.each do |key, val|
    define_method(:"#{key.to_s}?") do
      self.role == val
    end
  end

  def full_name
    [first_name, last_name].join(' ').strip
  end

  private ##

  def send_welcome_email
    UserMailer.welcome_email(self).deliver
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  load_resource
  before_action :authenticate_user!
  before_action :set_user, only: [:edit, :destroy, :update, :show, :reset_password]
  before_action :check_manage_permissions, except: [:index, :settings, :edit_password, :update_password]
  before_action :check_read_permission, only: [:index, :show]

  def index
    @user_type = user_type
    @users = User.where(role: user_type)

    if params[:search].present?
      search =  params[:search]
      @users = @users.where("
        first_name iLike :q OR 
        last_name iLike :q OR 
        state iLike :q OR 
        email iLike :q OR 
        medicare_number iLike :q OR 
        medicaid_number iLike :q", q: "%#{search}%"
      )
    end

    if params[:gender].present?
      @users = @users.where(gender: params[:gender])
    end

    if params[:active].present?
      @users = @users.where(active: params[:active])
    end

    @users = @users.page(params[:page])
  end

  def show
  end

  def new
    @user = User.new(role: user_type)
  end

  def create
    @user = User.new(user_params)
    
    password = Devise.friendly_token.first(8)
    @user.password = password
    @user.password_confirmation =  password
    @user.confirmed_at = Time.now

    authorize!(:manage, @user)

    if @user.save
      flash[:notice] = "User is created"
      redirect_to users_path(type: @user.role)
    else
      flash[:alert] = @user.errors.full_messages.to_sentence
      render action: :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User is saved"
      redirect_to users_path(type: @user.role)
    else
      flash[:alert] = @user.errors.full_messages.to_sentence
      render action: :edit
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = "User is destroyed"
    redirect_to users_path(type: @user.role)
  end

  def reset_password
    @user.send_reset_password_instructions
    flash[:notice] = "Reset password email is sent"
    redirect_to users_path(type: @user.role)
  end

  def settings
  end

  def edit_password
    @user = current_user
  end

  def update_password
    @user = current_user
    if @user.update(user_params)
      # Sign in the user by passing validation in case their password changed
      bypass_sign_in(@user)
        flash[:notice] = "Password is updated"
        redirect_to root_path
    else
      flash[:alert] = "Something worng please try again"
      render "edit_password"
    end
  end

  private ##

  def user_params
    params.require(:user).permit!
  end

  def set_user
    @user = User.find(params[:id])
  end

  def check_manage_permissions
    if @user.present? 
      authorize!(:manage, @user)
    else
      authorize!(:manage, user_type.to_sym)
    end
  end

  def check_read_permission
    authorize!(:read, user_type.to_sym)
  end

  def user_type
    params[:type] || 'individual'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    br

app/views/users/shared/_sigin_form.html.slim
= form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: 'frombox'}) do |f|
  .form-group
    = f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control', placeholder: 'Email Address '
  .form-group
    = f.password_field :password, autocomplete: "off", class: 'form-control', placeholder: 'Password '
  
  button.btn.btn-default[type="submit"]
    | Sign In

= render 'users/shared/links'

app/views/users/shared/_signup_form.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: 'fromlist'}) do |f| %>
    <div class="clearfix">
    <%= f.fields_for :company do |ff| %>
        <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
          <div class="form-group">
            <%= ff.label :company_type, "User Type", style: 'opacity: .5;' %><br />
            <%= ff.select(:company_type, ['Service Provider','Individual'], {}, { :class => 'form-control chosen-select', required: true}) %>
          </div>

          <div class="form-group">
            <%= ff.label :state, "State", style: 'opacity: .5;' %><br />
            <%= ff.select(:state, [], {}, { :class => 'form-control chosen-select', required: true}) %>
          </div>
          <div class="form-group">
            <%= ff.text_field :phone, class: 'form-control', required: true %>
            <%= ff.label :phone, class: 'form-control-placeholder' %>
          </div>

          <div class="form-group">
            <%= ff.text_field :address_2,class: 'form-control', required: true %>
            <%= ff.label :address_2, class: 'form-control-placeholder' %>
          </div>
        </div>
        <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
          <div class="form-group" id="city-load">
            <%= ff.label :country, "Country", style: 'opacity: .5;' %><br />
            <%= ff.select(:country, CS.countries.collect { |key, val| [val, key] }, {}, { :class => 'form-control chosen-select', required: true}) %>
          </div>
          <div class="form-group" id="city-load">
            <%= ff.label :city, "City", style: 'opacity: .5;' %><br />
            <%= ff.select(:city, [], {}, { :class => 'form-control chosen-select', required: true}) %>
          </div>

          <div class="form-group">
            <%= ff.text_field :address_1,class: 'form-control' %>
            <%= ff.label :address_1, class: 'form-control-placeholder' %>
          </div>

          <div class="form-group">
            <%= ff.text_field :zip,class: 'form-control' %>
            <%= ff.label :zip, class: 'form-control-placeholder' %>
          </div>
        </div>
    <% end %>
    </div>

    <div class="clearfix">
    <div class="col-md-12 col-sm-12 col-lg-12 medicaldics">Account Details</div>

    <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
      <div class="form-group">
        <%= f.email_field :email ,class: 'form-control'%>
        <%= f.label :email, class: 'form-control-placeholder' %>
      </div>
      <div class="form-group">
        <%= f.text_field :last_name,class: 'form-control'%>
        <%= f.label :last_name, class: 'form-control-placeholder' %>
      </div>
      <div class="form-group">
        <%= f.password_field :password_confirmation, autocomplete: "off",class: 'form-control'%>
        <%= f.label :password_confirmation, class: 'form-control-placeholder' %>
      </div>
    </div>

    <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
      <div class="form-group">
        <%= f.text_field :first_name,class: 'form-control'%>
        <%= f.label :first_name, class: 'form-control-placeholder' %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, autocomplete: "off",class: 'form-control' %>
        <%= f.label :password, class: 'form-control-placeholder' %>
      </div>
    </div>
    </div>

      <div class="checkleft" style="margin-left: 40px;">
        <div class="radio">
          <input name="optionsRadios" id="optionsRadios1" value="option1" checked="" type="radio">
          <label for="optionsRadios1">I agree to the Health Terms of Service & I certify that I have read and agree the Health Privacy Policy & Health Business Associate Agreement </label>
        </div>
      </div>

    <div class="col-md-12 col-sm-12 savebut">
      <button type="submit" class="btn btn-default">Sign Up</button>
    </div>
<%end%>

<script type="text/javascript">
  $('.chosen-select').chosen({

  });

    $('#user_company_state').change(function() {
      var state = $(this).val()
      var country = $('#user_company_country').val();
      $.ajax({
        type: 'get',
        url: '<%= load_cities_path %>',
        data: {state: state, country: country},
        dataType: 'script',
      });
    });

  $('#user_company_country').change(function() {
    var country = $(this).val()
    $.ajax({
      type: 'get',
      url: '<%= load_state_path %>',
      data: {country: country, id: 'user_company_state'},
      dataType: 'script',
    });
  });
</script>