config/routes.rb
Rails.application.routes.draw do
  get 'docs/index'
  devise_for :users, path: 'auth', :controllers => {:registrations => "registrations",  confirmations: 'confirmations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  
  resources :bsp_trainings
  resources :llc_services
  resources :medications
  resources :medication_counts
  resources :mars
  resources :behaviors
  resources :docs

  resources :users do
    get :reset_password, on: :member
    get 'settings', on: :collection
    get 'edit_password', on: :collection
    put 'update_password', on: :collection
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  belongs_to :company, optional: true
  has_many :bsp_trainings
  has_many :llc_services
  has_many :medications
  has_many :medication_counts
  has_many :mars
  has_many :behaviors

  has_and_belongs_to_many :service_types

  after_create :send_welcome_email
  
  ROLES = {
    super_admin: 'super_admin',
    admin: 'admin',
    staff: 'staff',
    individual: 'individual'
  }

  ROLES.each do |key, val|
    define_method(:"#{key.to_s}?") do
      self.role == val
    end
  end

  def full_name
    [first_name, last_name].join(' ').strip
  end

  private ##

  def send_welcome_email
    UserMailer.welcome_email(self).deliver
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  load_resource
  before_action :authenticate_user!
  before_action :set_user, only: [:edit, :destroy, :update, :show, :reset_password]
  before_action :check_manage_permissions, except: [:index, :settings, :edit_password, :update_password]
  before_action :check_read_permission, only: [:index, :show]

  def index
    @user_type = user_type
    @users = User.where(role: user_type)

    if params[:search].present?
      search =  params[:search]
      @users = @users.where("
        first_name iLike :q OR 
        last_name iLike :q OR 
        state iLike :q OR 
        email iLike :q OR 
        medicare_number iLike :q OR 
        medicaid_number iLike :q", q: "%#{search}%"
      )
    end

    if params[:gender].present?
      @users = @users.where(gender: params[:gender])
    end

    if params[:active].present?
      @users = @users.where(active: params[:active])
    end

    @users = @users.page(params[:page])
  end

  def show
  end

  def new
    @user = User.new(role: user_type)
  end

  def create
    @user = User.new(user_params)
    
    password = Devise.friendly_token.first(8)
    @user.password = password
    @user.password_confirmation =  password
    @user.confirmed_at = Time.now

    authorize!(:manage, @user)

    if @user.save
      flash[:notice] = "User is created"
      redirect_to users_path(type: @user.role)
    else
      flash[:alert] = @user.errors.full_messages.to_sentence
      render action: :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User is saved"
      redirect_to users_path(type: @user.role)
    else
      flash[:alert] = @user.errors.full_messages.to_sentence
      render action: :edit
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = "User is destroyed"
    redirect_to users_path(type: @user.role)
  end

  def reset_password
    @user.send_reset_password_instructions
    flash[:notice] = "Reset password email is sent"
    redirect_to users_path(type: @user.role)
  end

  def settings
  end

  def edit_password
    @user = current_user
  end

  def update_password
    @user = current_user
    if @user.update(user_params)
      # Sign in the user by passing validation in case their password changed
      bypass_sign_in(@user)
        flash[:notice] = "Password is updated"
        redirect_to root_path
    else
      flash[:alert] = "Something worng please try again"
      render "edit_password"
    end
  end

  private ##

  def user_params
    params.require(:user).permit!
  end

  def set_user
    @user = User.find(params[:id])
  end

  def check_manage_permissions
    if @user.present? 
      authorize!(:manage, @user)
    else
      authorize!(:manage, user_type.to_sym)
    end
  end

  def check_read_permission
    authorize!(:read, user_type.to_sym)
  end

  def user_type
    params[:type] || 'individual'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_filter.html.slim
#filter.row
  .col-lg-8
    span Filter

    form.auto-submit
      = hidden_field_tag :type, params[:type]
      ul.list_select
        li
          = select_tag :active, options_for_select([['Active', true], ['Inactive', false]], params[:active]), include_blank: '-- Status -- ', class: 'form-control'

        li
          = select_tag :gender, options_for_select([['Male', 'male'], ['Female', 'female']], params[:gender]), include_blank: '-- Gender -- ', class: 'form-control'
            
  .searchbox.col-lg-4
    .form-group
      .fa.fa-search
      = form_tag(users_path, method: :get)  do
        = text_field_tag(:search, params[:search], class: 'form-control' )
        = hidden_field_tag :type, params[:type]
        

app/views/users/_form.html.slim
=  f.hidden_field(:role, value: f.object.role)

- unless @user.individual?
  .form-group.row
    .col-lg-6
      = f.text_field :individual_id, class: 'form-control', required: true
      = f.label :individual_id, 'Id', class: 'form-control-placeholder'

.form-group.row
  .col-lg-6
    = f.text_field :first_name,class: 'form-control', required: true
    = f.label :first_name,  class: 'form-control-placeholder'
  .col-lg-6
    = f.text_field :last_name,class: 'form-control', required: true
    = f.label :last_name,  class: 'form-control-placeholder'

.form-group.row
  .col-lg-6
    = f.email_field :email,class: 'form-control', required: true
    = f.label :email,'Email Address',  class: 'form-control-placeholder'

  .col-lg-6
    label.radio-inline
      = f.radio_button :gender, 'male', checked: @user.gender == 'male' || @user.gender.nil?
      |  Male 
    label.radio-inline
      = f.radio_button :gender, 'female'
      |  Female 

.form-group.row
  .col-lg-6
    = f.text_field :telephone,class: 'form-control',required: true
    = f.label :telephone, 'Telephone', class: 'form-control-placeholder'
  .col-lg-6
    = f.text_field :phone,class: 'form-control', required: true
    = f.label :phone,'Cell Phone',  class: 'form-control-placeholder'

- if @user.individual?
  .form-group.row
    .col-lg-6
      = f.text_field :medicare_number,class: 'form-control', required: true
      = f.label :medicare_number,  class: 'form-control-placeholder'

    .col-lg-6
      = f.text_field :medicaid_number,class: 'form-control', required: true
      = f.label :medicaid_number,  class: 'form-control-placeholder'

.form-group.row
  .col-lg-6
    = f.text_field :tabs_id,class: 'form-control', required: true
    = f.label :tabs_id,'TABS ID',  class: 'form-control-placeholder'

  - if @user.staff?
    .col-lg-6
      = f.label :service_type_ids, "Service Types", class: 'form-control-placeholder'
      = f.select(:service_type_ids, options_from_collection_for_select(ServiceType.all, :id, :name, f.object.service_type_ids), {}, { :class => 'form-control chosen-select', multiple: true })

.form-group.row
  .col-lg-6
    = f.text_field :address_1,class: 'form-control', required: true
    = f.label :address_1,  class: 'form-control-placeholder'
  
  .col-lg-6
    = f.text_field :address_2,class: 'form-control', required: true
    = f.label :address_2,  class: 'form-control-placeholder'

.form-group.row
  .col-lg-6
    = f.label :state, "State", style: 'opacity: .5;',  class: 'form-control-placeholder'
    = f.select(:state, CS.states('us').map {|item| [item.last, item.first]}, {}, { :class => 'form-control chosen-select', required: true})
  
  .col-lg-6
    = f.text_field :zip,class: 'form-control', required: true
    = f.label :zip,  class: 'form-control-placeholder'

.form-group.row
  .col-lg-6
    label.radio-inline.no-padding
      = f.check_box :active
      = f.label :active

.form-group.savebut
  button.btn.btn-default[type="submit"] Save

app/views/users/edit.html.slim
#page-wrapper
  .panel.panel-default
    .panel-heading  
      h1 Edit #{@user.role.capitalize}
    .panel-body
      = form_for(@user, html: {class: 'fromlist'}) do |f|
        = render 'form', f: f

app/views/users/edit_password.html.erb
<div id="page-wrapper">
  <div class="row">
    <p>&nbsp;</p>
        <%= form_for(@user, url: update_password_users_path, method: "put", html: {class: 'fromlist'}) do |f| %>

        <div class="form-group">
          <%= f.password_field :password, autocomplete: "off",class: 'form-control' %>
          <%= f.label :password, class: 'form-control-placeholder' %>
        </div>
        <div class="form-group">
          <%= f.password_field :password_confirmation, autocomplete: "off",class: 'form-control'%>
          <%= f.label :password_confirmation, class: 'form-control-placeholder' %>
        </div>
            <button type="submit" class="btn btn-default">Update Password</button>
        <% end %>
      </div>
</div>

app/views/users/index.html.slim
#page-wrapper
  .panel.panel-default
    .panel-heading.indiviuals_list
      = render 'filter'

    .panel-body
      .table-responsive
        table.table.table-striped.table-bordered.table-hover
          thead
            tr
              th
                | S. No.
              th
                | ID
              th
                | First Name
              th
                | Last Name
              th
                | Status

          tbody
            - @users.each_with_index do |user ,i|
              tr
                td
                  = i + 1
                td
                  = link_to user_path(user) do
                    = user.id
                td
                  = user.first_name
                td
                  = user.last_name
                td
                  - if user.active?
                    = image_tag 'active.png'
                  - else
                    |  Inactive 
                
                - if can?(:manage, user)
                  td
                    = link_to edit_user_path(user) do
                      .fa.fa-pencil
                      |  Edit

                    = ' | '
                    = link_to user_path(user), data: { method: :delete, confirm: 'Are you sure to delete?' } do
                      .fa.fa-times.mr-2
                      | Delete

                    = ' | '
                    = link_to user_path(user) do
                      .fa.fa-eye
                      | View
                   
                    = ' | '
                    = link_to reset_password_user_path(user) do
                      .fa.fa-key
                      | Reset password

        = paginate @users
        
    = link_to 'Add New Entry', new_user_path(type: params[:type]), class: 'btn add_entry' if can?(:manage, User)

app/views/users/new.html.slim
#page-wrapper
  .panel.panel-default
    .panel-heading  
      h1 Create #{@user.role.capitalize}
    .panel-body
      = form_for(@user, html: {class: 'fromlist'}) do |f|
        = render 'form', f: f

app/views/users/settings.html.slim
#page-wrapper
  .row
    p
      |  
    .listtime
      ul
        li
          = image_tag 'billing1.png'
        li
          = image_tag 'billing2.png'
        li
          = image_tag 'billing3.png'
        li
          = image_tag 'billing4.png'
        li
          = link_to edit_password_users_path  do
            = image_tag 'billing5.png'
        li
          = image_tag 'billing6.png'

app/views/users/show.html.slim
#page-wrapper
  .panel.panel-default
    .panel-heading  
      .clearfix
        h1.pull-left
          = @user.full_name
          = " (#{@user.active? ? 'Active' : ''})"

        .pull-right
          = link_to users_path(@user.role) do
            h1.fa.fa-mail-reply.fa-2x

    .panel-body
      .details
        - unless @user.individual?
          .form-group.row
            label.col-lg-2 ID:
            .col-lg-3= @user.individual_id

        .form-group.row
          label.col-lg-2 First name:
          .col-lg-3= @user.first_name

          label.col-lg-2 Last name:
          .col-lg-3= @user.last_name


        .form-group.row
          label.col-lg-2 Email:
          .col-lg-3= @user.email

          label.col-lg-2 Gender:
          .col-lg-3= @user.gender.try(:capitalize)

        .form-group.row
          label.col-lg-2 Telephone:
          .col-lg-3= @user.telephone

          label.col-lg-2 Cell Phone:
          .col-lg-3= @user.phone

        - if @user.individual?
          .form-group.row
            label.col-lg-2 Medicare Number:
            .col-lg-3= @user.medicare_number

            label.col-lg-2 Medicaid number:
            .col-lg-3= @user.medicaid_number

      
        .form-group.row
          label.col-lg-2 TABS ID:
          .col-lg-3= @user.tabs_id

          - if @user.staff?
            label.col-lg-2 Service Types:
            .col-lg-3= @user.service_types.map(&:name).join(', ')

        .form-group.row
          label.col-lg-2 Address 1:
          .col-lg-3= @user.address_1

          label.col-lg-2 Address 2:
          .col-lg-3= @user.address_2


        .form-group.row
          label.col-lg-2 State::
          .col-lg-3= CS.states('us')[@user.state.to_sym] rescue nil

          label.col-lg-2 Zip:
          .col-lg-3= @user.zip

     