config/routes.rb
Rails.application.routes.draw do
  get 'docs/index'
  devise_for :users, path: 'auth', :controllers => {:registrations => "registrations",  confirmations: 'confirmations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  
  resources :bsp_trainings
  resources :llc_services
  resources :medications
  resources :medication_counts
  resources :mars
  resources :behaviors
  resources :docs

  resources :users do
    get :reset_password, on: :member
    get 'settings', on: :collection
    get 'edit_password', on: :collection
    put 'update_password', on: :collection
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.super_admin?
      super_admin_permissions(user)
    elsif user.admin?
      admin_permissions(user)
    elsif user.staff?
      staff_permissions(user)
    elsif user.individual?
      individual_permissions(user)
    else
      can :read, :all
    end
  end

  private ##

  def super_admin_permissions(user)
    can :manage, User
    can :manage, :admin
    can :manage, :staff
    can :manage, :individual

    can :manage, Doc
  end

  def admin_permissions(user)
    can :manage, :staff
    can :manage, :individual
    can :manage, User do |user|
      %w(staff individual).include?(user.role)
    end

    can :manage, Doc
  end

  def staff_permissions(user)
    can :read, :individual
    can :read, User do |user|
      user.individual?
    end
  end

  def individual_permissions(user)
  end
end

app/models/behavior.rb
class Behavior < ApplicationRecord
  belongs_to :user

  has_one :restricted_measure, dependent: :destroy
  accepts_nested_attributes_for :restricted_measure

  has_many :behavior_outcomes, dependent: :destroy
  accepts_nested_attributes_for :behavior_outcomes, allow_destroy: true, reject_if: :all_blank

  has_many :signature_lists, as: :signatureable, dependent: :destroy
  accepts_nested_attributes_for :signature_lists, allow_destroy: true, reject_if: :all_blank
end

app/models/behavior_outcome.rb
class BehaviorOutcome < ApplicationRecord
  belongs_to :behavior
end

app/models/bsp_training.rb
class BspTraining < ApplicationRecord
   belongs_to :company
  belongs_to :user
end

app/models/change_service.rb
class ChangeService < ApplicationRecord
  belongs_to :change_serviceable, polymorphic: true, optional: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :bsp_trainings
  has_many :llc_services
  has_many :medications
  has_many :medication_counts
  has_many :mars
  has_many :behaviors


  User::ROLES.each do |key, val|
    define_method(:"#{key.to_s}s") do
      self.users.where(role: val)
    end
  end
  # def individuals
  #   self.users.where(admin: false)
  # end
end

app/models/doc.rb
class Doc < ApplicationRecord
  has_attached_file :file
  validates_attachment_content_type :file, :content_type => ['application/pdf']

  belongs_to :user, required: false
  enum doc_type: [:isp, :bsp]
end

app/models/hpc_service.rb
class HpcService < ApplicationRecord
  belongs_to :hpc_serviceable, polymorphic: true, optional: true
end

app/models/ist_information.rb
class IstInformation < ApplicationRecord
  belongs_to :medication
end

app/models/llc_service.rb
class LlcService < ApplicationRecord
  has_one :hpc_service, as: :hpc_serviceable, dependent: :destroy
  accepts_nested_attributes_for :hpc_service

  has_many :location_services, as: :location_serviceable, dependent: :destroy
  accepts_nested_attributes_for :location_services, allow_destroy: true, reject_if: :all_blank

  has_many :change_services, as: :change_serviceable, dependent: :destroy
  accepts_nested_attributes_for :change_services, allow_destroy: true, reject_if: :all_blank

  has_many :signature_lists, as: :signatureable, dependent: :destroy
  accepts_nested_attributes_for :signature_lists, allow_destroy: true, reject_if: :all_blank

  belongs_to :company
  belongs_to :user
end

app/models/mar.rb
class Mar < ApplicationRecord
  belongs_to :company
  belongs_to :user
  has_many :medication_items, dependent: :destroy
  accepts_nested_attributes_for :medication_items, allow_destroy: true, reject_if: :all_blank

  has_many :medication_documents, dependent: :destroy
  accepts_nested_attributes_for :medication_documents, allow_destroy: true, reject_if: :all_blank

  has_many :signature_lists, as: :signatureable, dependent: :destroy
  accepts_nested_attributes_for :signature_lists, allow_destroy: true, reject_if: :all_blank
end

app/models/medication.rb
class Medication < ApplicationRecord
  belongs_to :company
  belongs_to :user

  has_many :ist_informations, dependent: :destroy
  accepts_nested_attributes_for :ist_informations, allow_destroy: true, reject_if: :all_blank

  MEDICATION_TYPE = ['Oral', 'Inhaler', 'Optic (Rt eye /Lt eye)', 'Rectal', 'Subcutaneous', 'Sublingual', 'Nebulizer', 'Otic(Rt eye /Lt ear)', 'Vaginal', 'Insulin', 'Glucagon', 'EpiPen']

end

app/models/medication_item.rb
class MedicationItem < ApplicationRecord
  belongs_to :mar
end

app/models/service_type.rb
class ServiceType < ApplicationRecord
  has_and_belongs_to_many :users

  default_scope -> { order(id: :asc) }
end

app/models/signature_list.rb
class SignatureList < ApplicationRecord
  belongs_to :signatureable, polymorphic: true, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  belongs_to :company, optional: true
  has_many :bsp_trainings
  has_many :llc_services
  has_many :medications
  has_many :medication_counts
  has_many :mars
  has_many :behaviors

  has_and_belongs_to_many :service_types

  after_create :send_welcome_email
  
  ROLES = {
    super_admin: 'super_admin',
    admin: 'admin',
    staff: 'staff',
    individual: 'individual'
  }

  ROLES.each do |key, val|
    define_method(:"#{key.to_s}?") do
      self.role == val
    end
  end

  def full_name
    [first_name, last_name].join(' ').strip
  end

  private ##

  def send_welcome_email
    UserMailer.welcome_email(self).deliver
  end
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/mars_helper.rb
module MarsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.slim
doctype html
html
  =  render 'shared/head'
  body class="#{controller_name} #{action_name}"
    #wrapper
      - if current_user.present?
        = render 'shared/left_nav'
      - else
        = render 'shared/nav'
        
      = render 'shared/flash_message'
      = render 'shared/notification'
      = yield

app/views/layouts/devise.html.slim
doctype html
html
  =  render 'shared/head'
  body class="#{controller_name} #{action_name}"
    #wrapper
      - if current_user.present?
        = render 'shared/left_nav'
      - else
        = render 'shared/nav'
        
      = render 'shared/flash_message'
      = render 'shared/notification'
      br/
      .col-lg-6.col-lg-offset-3
        .panel.panel-default
          = yield

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edocuments</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <style type="text/css">
    .main-wrap {
      margin: 30px auto;
      padding: 20px;
    }

    .medication-count-table {
      width: 100%;
      border: 2px solid #333;
      border-collapse: collapse;
    }

    .medication-count-table th,
    .medication-count-table td {
      border: 2px solid #333;
      padding: 0.5rem 2rem;
    }

    .medication-count-table td {
      /*white-space: nowrap;*/
    }

    .medication-count-table th {
      font-weight: normal;
    }

    .medication-count-table td {
      border-style: none solid;
      vertical-align: top;
    }

    .medication-count-table th {
      padding: 0.2em;
      vertical-align: middle;
      /*text-align: center;*/
    }

    .medication-count-table thead tr.title-list > th {
      text-align: center;
    }

    /* Mar table */
    table.mar-table tbody{
      font-size: 10px;
      font-weight: bold;
    }
    /* Mar table */

    .headline {
      border: 4px double #333;
    }
    .doc-info li span {
      text-align: right;
      border-bottom: 2px solid #333;
      margin-left: 15px;
      margin-bottom: 8px;
      display: inline-block;
    }

    .hints div, .service-key i {
      font-weight: normal;
      font-size: 10px;
    }

    .info-wrap {
      border: 1px solid #333;
      padding: 15px;
      max-width: 800px;
      margin: auto;
    }

    .span-underline {
      position: relative;
    }
    .span-underline::before {
      position: absolute;
      content: '';
      height: 1px;
      bottom: 0;
      left: 0px;
      right: 0px;
      min-width: 100%;
      border-bottom: 1px dashed #333;
    }

    .route-list li {
      margin-right: 15px;
      display: inline-block;
      position: relative;
    }

    .route-list li span.check-mark {
      padding-left: 20px;
      position: relative;
      vertical-align: top;
    }

    .route-list li span.check-mark::before {
      position: absolute;
      content: '';
      width: 15px;
      height: 15px;
      border: 1px solid #333;
      vertical-align: middle;
      left: 0;
      bottom: 2px;
    }

    .checkmark{
      display:inline-block;
    }

    .checkmark::after{
      content: '';
      display: block;
      width: 6px;
      height: 12px;
      border: solid #000;
      border-width: 0 2px 2px 0;
      transform: rotate(45deg);
      -webkit-transform: rotate(45deg);
      position: absolute;
      top: 0px;
      left: 5px;
    }

    /* Some extra css for tally table */
    /* borderless table */
    .table.table-borderless td, .table.table-borderless th {
      border: 0 !important;
    }

    .table.table-borderless {
      margin-bottom: 0px;
    }
    .mb-20 {
      margin-bottom: 20px;
    }
    .common-ul-style {
      padding: 0;
      margin: 0;
      list-style-type: none;
    }
    .para-hr {
      border-bottom: 2px solid #333;
      margin-left: -10px;
      margin-right: -10px;
    }
    .left-sm-text {
      text-align: left;
      font-size: 8px;
      vertical-align: top;
    }
    .right-sm-text {
      text-align: right;
      font-size: 8px;
      vertical-align: bottom;
    }
    .flexible-td {
      word-wrap: break-word;
      white-space: inherit;
    }
    .l-border-transparent {
      border-left: transparent !important;
    }
    .r-border-transparent {
      border-right: transparent !important;
    }
    .space {
      height: 50px;
    }
    .width-55 {
      width: 55px;
    }
    .min-width-60 {
      min-width: 60px;
    }
    .min-width-250 {
      min-width: 250px;
    }
    .table-area-field100 {
      height: 100px;
    }
    .table-area-field100 > th {
      vertical-align: top !important;
    }

    /* Bootstrap customization for tally table design */
    .table {
      font-size: 16px;
    }

    .table > thead > tr > th {
      vertical-align: bottom;
      border-bottom: 2px solid #333;
    }

    .table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td, .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th {
      border-top: 2px solid #333;
    }

    .mar-table > thead > tr > th {
      font-size: 11px;
      font-weight: bold;
    }

    .mar-table > tbody > tr > td {
      font-size: 11px;
      font-weight: bold;
    }
  </style>
</head>
<body>


<div class='container'>
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_change_service_item.html.erb
<div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
  <div class="form-group">
    <%= text_field_tag "llc_service[change_services_attributes][serial_number][description]", nil, class: "form-control" %>
    <%= label_tag 'Description', nil ,class: 'form-control-placeholder', for: 'llc_service_change_services_attributes_serial_number_description' %>
  </div>
</div>

<div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
  <div class="form-group">
    <%= text_field_tag "llc_service[change_services_attributes][serial_number][date]", nil, class: "form-control datepicker" %>
    <%= label_tag 'Date', nil ,class: 'form-control-placeholder', for: 'llc_service_change_services_attributes_serial_number_date' %>
  </div>
</div>

<script type="text/javascript">
  $('.datepicker').datepicker({format: 'yyyy/mm/dd'});
</script>

app/views/shared/_change_services.html.erb
  <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
    <div class="form-group">
      <%= cs.text_field :description, class: "form-control" %>
      <%= cs.label :description, nil ,class: 'form-control-placeholder' %>
    </div>
  </div>

  <div class="col-md-4 col-sm-6 col-lg-4 col-xs-12">
    <div class="form-group">
      <%= cs.text_field :date, class: "form-control datepicker" %>
      <%= cs.label :date, nil ,class: 'form-control-placeholder' %>
    </div>
  </div>

  <div class="col-sm-2">
    <%= cs.check_box :_destroy %>
    <%= cs.label :delete%>
  </div>

  <script type="text/javascript">
    $('.datepicker').datepicker({format: 'yyyy/mm/dd'});
  </script>

app/views/shared/_flash_message.html.erb
<script type="text/javascript">
    $(function () {
        <% flash.each do |name, msg| -%>
        popupMessage("<%=raw msg %>", "<%= flash_types.include?(name)  ? "alert-#{ name }" : "alert-info" %>");
        <% end -%>
        <% flash.clear %>
    });
</script>

app/views/shared/_head.html.erb
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Q C L S</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
        type="text/css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

app/views/shared/_hpc_service.html.erb
<div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
  <div class="form-group">
    <%= hpcs.text_field :path_to_employment,class: 'form-control', required: true %>
    <%= hpcs.label :path_to_employment, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :staff_assistance,class: 'form-control', required: true %>
    <%= hpcs.label :staff_assistance, class: 'form-control-placeholder' %>
  </div>
  <div class="form-group">
    <%= hpcs.text_field :assist_with_learning_work,class: 'form-control', required: true %>
    <%= hpcs.label :assist_with_learning_work, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :assist_developing_skills,class: 'form-control', required: true %>
    <%= hpcs.label :assist_developing_skills, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :assistance_with_cooking_planing,class: 'form-control', required: true %>
    <%= hpcs.label :assistance_with_cooking_planing, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :assistance_with_cooking_lunch,class: 'form-control', required: true %>
    <%= hpcs.label :assistance_with_cooking_lunch, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :assistance_with_snack,class: 'form-control', required: true %>
    <%= hpcs.label :assistance_with_snack, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :assist_with_household_chores,class: 'form-control', required: true %>
    <%= hpcs.label :assist_with_household_chores, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :assist_to_stay_on_task,class: 'form-control', required: true %>
    <%= hpcs.label :assist_to_stay_on_task, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :liesure_activities_which_he_loves,class: 'form-control', required: true %>
    <%= hpcs.label :liesure_activities_which_he_loves, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :assist_with_learning_to_budget_money,class: 'form-control', required: true %>
    <%= hpcs.label :assist_with_learning_to_budget_money, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :give_individual_for_friday,class: 'form-control', required: true %>
    <%= hpcs.label :give_individual_for_friday, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :assist_with_household_maintenance,class: 'form-control', required: true %>
    <%= hpcs.label :assist_with_household_maintenance, class: 'form-control-placeholder' %>
  </div>
</div>

<div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
  <div class="form-group">
    <%= hpcs.text_field :self_administered_medication,class: 'form-control', required: true %>
    <%= hpcs.label :self_administered_medication, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :provide_supervision,class: 'form-control', required: true %>
    <%= hpcs.label :provide_supervision, class: 'form-control-placeholder' %>
  </div>
  <div class="form-group">
    <%= hpcs.text_field :assist_coping_skills,class: 'form-control', required: true %>
    <%= hpcs.label :assist_coping_skills, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :assist_maintaining_diet_control,class: 'form-control', required: true %>
    <%= hpcs.label :assist_maintaining_diet_control, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :assistance_with_cooking_breakfast,class: 'form-control', required: true %>
    <%= hpcs.label :assistance_with_cooking_breakfast, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :assistance_with_cooking_dinner,class: 'form-control', required: true %>
    <%= hpcs.label :assistance_with_cooking_dinner, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :liesure_activities,class: 'form-control', required: true %>
    <%= hpcs.label :liesure_activities, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :assist_with_laundry,class: 'form-control', required: true %>
    <%= hpcs.label :assist_with_laundry, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :provide_assist_with_reminding_to_shower,class: 'form-control', required: true %>
    <%= hpcs.label :provide_assist_with_reminding_to_shower, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :encourage_to_work_for_his_own_money,class: 'form-control', required: true %>
    <%= hpcs.label :encourage_to_work_for_his_own_money, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :assist_with_shopping,class: 'form-control', required: true %>
    <%= hpcs.label :assist_with_shopping, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :assist_with_laccessing_the_community,class: 'form-control', required: true %>
    <%= hpcs.label :assist_with_laccessing_the_community, class: 'form-control-placeholder' %>
  </div>

  <div class="form-group">
    <%= hpcs.text_field :night_on_site_on_call,class: 'form-control', required: true %>
    <%= hpcs.label :night_on_site_on_call, class: 'form-control-placeholder' %>
  </div>
</div>

app/views/shared/_left_nav.html.slim
nav.navbar.navbar-default.navbar-static-top[role="navigation" style="margin-bottom: 0"]
  .navbar-header.col-md-6
    button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
      span.sr-only
        | Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar
    a.navbar-brand[href=root_path]
      = image_tag 'logo.png', alt: ''
    span
      | Quality Comfort Living Services LLC
  ul.nav.navbar-top-links.navbar-right
    li.dropdown
      a.dropdown-toggle[href="#"]
        .fa.fa-check-circle-o
        |  Save 
    li.dropdown
      a.dropdown-toggle[href="#"]
        .fa.fa-print
        | Print 
    li.dropdown
      a.dropdown-toggle.save-as-pdf[data-toggle="dropdown" href="javascript:void(0)"]
        .fa.fa-file-text-o
        | Save As PDF 

  .navbar-default.sidebar[role="navigation"]
    .sidebar-nav.navbar-collapse
      ul#side-menu.nav
        li
          = link_to settings_users_path do
            .fa.fa-cog
            |  Settings

        - if can? :read, :individual
          li
            a[href="javascript:;"]
              .fa.fa-users
              |  Users
            ul.nav.nav-second-level.collapse class=(controller_name == 'users' && action_name != 'settings' ? 'in' : '')
              - if can? :read, :admin
                li
                  = link_to 'Admin', users_path(type: 'admin')
              - if can? :read, :staff
                li
                  = link_to 'Staff', users_path(type: 'staff')
              - if can? :read, :individual
                li
                  = link_to 'Individuals', users_path(type: 'individual')
      
        li
          a[href="javascript:;"]
            .fa.fa-life-bouy
            |  eDoc Suite
          ul.nav.nav-second-level.collapse class=(['bsp_trainings', 'llc_services', 'behaviors', 'medications', 'medication_counts', 'mars', 'docs'].include?(controller_name) ? 'in' : '')
            li
              a[href="javascript:;"]
                | ISP/BSP
              ul.nav.nav-second-level.collapse.sub-menu class=(active_class('docs'))
                li
                  = link_to 'ISP', docs_path(type: :isp)
                li
                  = link_to 'BSP', docs_path(type: :bsp)
                li
                  = link_to 'ISP/BSP Training', bsp_trainings_path
            li
              = link_to 'Services LLC', llc_services_path
            li
              = link_to 'Monthly Behavior Support Data', behaviors_path
            li
              = link_to 'Medications', medications_path
            li
              = link_to 'Medication Counts', medication_counts_path
            li
              = link_to 'Medication Adminstration Records', mars_path
        li
          a[href="javascript:;"]
            .fa.fa-cube
            |  Folders
        li
          a[href="javascript:;"]
            .fa.fa-calendar
            |  Calendars
        li
          a[href="javascript:;"]
            .fa.fa-headphones
            |  Help and Support
        li
          = link_to destroy_user_session_path(:authenticity_token => form_authenticity_token()), method: 'delete' do
            .fa.fa-power-off
            |  Logout 

app/views/shared/_location_service_item.html.erb
<div class="col-md-4 col-sm-4 col-lg-4">
  <div class="form-group">
    <%= text_field_tag "llc_service[location_services_attributes][serial_number][location]", nil, class: "form-control" %>
    <%= label_tag 'Location',nil ,class: 'form-control-placeholder', for: 'llc_service_location_services_attributes_serial_number_location' %>
  </div>
</div>
<div class="col-md-4 col-sm-4 col-lg-4">
  <div class="form-group">
    <%= text_field_tag "llc_service[location_services_attributes][serial_number][initials]", nil, class: "form-control" %>
    <%= label_tag 'Initials',nil ,class: 'form-control-placeholder', for: 'llc_service_location_services_attributes_serial_number_initials' %>
  </div>
</div>
<div class="col-md-4 col-sm-4 col-lg-4">
  <div class="form-group">
    <%= text_field_tag "llc_service[location_services_attributes][serial_number][date]", nil, class: "form-control datepicker" %>
    <%= label_tag 'Date',nil ,class: 'form-control-placeholder', for: 'llc_service_location_services_attributes_serial_number_date' %>
  </div>
</div>

<script type="text/javascript">
  $('.datepicker').datepicker({format: 'yyyy/mm/dd'});
</script>

app/views/shared/_location_services.html.erb
  <div class="col-md-4 col-sm-4 col-lg-4">
    <div class="form-group">
      <%= ls.text_field :location, class: "form-control" %>
      <%= ls.label :location, nil ,class: 'form-control-placeholder' %>
    </div>
  </div>
  <div class="col-md-2 col-sm-2 col-lg-2">
    <div class="form-group">
      <%= ls.text_field :initials, class: "form-control" %>
      <%= ls.label :initials, nil ,class: 'form-control-placeholder' %>
    </div>
  </div>
  <div class="col-md-4 col-sm-4 col-lg-4">
    <div class="form-group">
      <%= ls.text_field :date, class: "form-control datepicker" %>
      <%= ls.label :date, nil ,class: 'form-control-placeholder' %>
    </div>
  </div>
  <div class="col-sm-2">
    <%= ls.check_box :_destroy %>
    <%= ls.label :delete%>
  </div>

app/views/shared/_notification.html.erb
<div id='notification' class="">
  <a id="notice-close" href="javascript:void(0)" class="close" aria-label="close">×</a>
  <p id="flash-msg-text" class="mr20"></p>
</div>